var documentRoot='http://127.0.0.1/academium';
var OMNISOFT_VALORIVA=0.12;
var OMNISOFT_TRIMESTRE='TRIMESTRE';
//var OMNISOFT_RED_COLEGIOS='UNIDAD EDUCATIVA PAULO VI';
var OMNISOFT_RED_COLEGIOS='CENTRO EDUCATIVO BILINGUE';
//var OMNISOFT_RED_COLEGIOS='Red de Colegios Lasallistas';
//var OMNISOFT_RED_COLEGIOS='Sociedad de Madres Salesianas';
//var OMNISOFT_FACTURA='FyA';
//var OMNISOFT_FACTURA='Cebi';
//var OMNISOFT_FACTURA='MARiobamba';
var OMNISOFT_FACTURA='LiceoInternacional';
var OMNISOFT_LIBRETA='Quito';
var OMNISOFT_COLEGIO='Liceo Internacional';
var OMNISOFT_DIASB=1;
var OMNISOFT_DIASC=30;



